image: rocker/verse:4.3.0

stages:
  - process
  - publish

default:
  cache:
    key:
      files:
        - renv.lock
    paths:
      - renv/
  before_script:
    - Rscript -e "renv::restore()"

internal:
  stage: process
  tags:
   - runner1
  script:
    - Rscript -e 'source("itf_dashboard/0_output_data.R")'

external:
  stage: process
  tags:
  - runner1
  script:
  - Rscript -e 'source("covid_data_tracker/0_output_data.R")'

publish:
  stage: publish
  needs: ["internal", "external"]
  tags:
  - runner1
  script:
  - Rscript -e 'source(".github/workflows/export_data.R")'
   