image: rocker/verse:4.3.0

stages:
  - process
  - publish

.standup:
  before_script:
    - Rscript -e "renv::restore()"

internal:
  stage: process
  extends: .standup
  tags:
   - runner1
  script:
    - Rscript -e 'source("itf_dashboard/0_output_data.R")'

external:
  stage: process
  extends: .standup
  tags:
  - runner1
  script:
  - Rscript -e 'source("covid_data_tracker/0_output_data.R")'

publish:
  stage: publish
  extends: .standup
  needs: ["internal", "external"]
  tags:
  - runner1
  script:
  - Rscript -e 'source(".github/workflows/export_data.R")'
   